name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello from Main
        run: echo "Hello from the Main branch!"
