name: QA Branch Workflow

on:
  push:
    branches:
      - QA

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello from QA
        run: echo "Hello from the QA branch!"
